Algoritmo "Leitura do antecessor"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ler um número e mostrar seu antecessor - Exercicio 5
// Autor(a)    : Stephany Camily dos Santos
// Data atual  : 20/03/2024
Var
    numero: inteiro

Inicio
      Escreval("Digite um número:")
      leia(numero)
      Escreval("O antecessor é:", numero -1)


Fimalgoritmo