Algoritmo "Maior que 10"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Ler um numero maior que 10 - Exercicio 14
// Autor(a)    : Stephany Camily dos Santos

Var
   valor: inteiro

Inicio
   Escreva("Digite um valor: ")
   Leia(valor)
   Se (valor > 10) Então
      Escreva("É maior que 10!")
   Senão
      Escreva("Não é maior que 10!")
   FimSe
FimAlgoritmo