Algoritmo "Área do losango"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostrar a área do losango - Exercicio proposto em aula
// Autor(a)    : Stephany Camily dos Santos

Var
     diagonal1, diagonal2: real

Inicio
      Escreva("Digite a primeira diagonal: ")
      Leia(diagonal1)
      Escreva("Digite a segunda diagonal: ")
      Leia(diagonal2)
      Escreval("A Área é: ", (diagonal1 * diagonal2) / 2)

Fimalgoritmo