Algoritmo "Área do Quadrado"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostrar a área do quadrado - Exercicio proposto em aula
// Autor(a)    : Stephany Camily dos Santos

Var
    base, lado: inteiro

Inicio
      Escreval("Area do Quadrado")
      Escreva("Digite o valor de um Lado: ")
      Leia(lado)
      Escreval("A Área é: ", lado * lado)

Fimalgoritmo