Algoritmo "Área do Retângulo"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostrar a área do retângulo - Exercicio 6
// Autor(a)    : Stephany Camily dos Santos

Var
    base, lado: inteiro

Inicio
      Escreval("Digite a base do retângulo: ")
      leia(base)
      Escreval("Digite o lado do retângulo: ")
      leia(lado)
      Escreval("A área é:", base*lado)


Fimalgoritmo