Algoritmo "Área do Triângulo"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Mostrar a área do triângulo - Exercicio proposto em aula
// Autor(a)    : Stephany Camily dos Santos

Var
    base, altura: inteiro

Inicio

      Escreva("Digite o valor da Base: ")
      Leia(base)
      Escreva("Digite o valor do Altura: ")
      Leia(altura)
      Escreval("A Área é: ", (base * altura) / 2)


Fimalgoritmo